name: zebrapose
channels:
   - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - torchvision==0.11.2
  - cython
  - scipy==1.5.1
  - kiwisolver==1.3.1
  - matplotlib==2.2.4
  - imageio==2.5.0
  - pypng
  - pyopengl
  - triangle
  - OpenCV
  - pillow
  - vispy
  - eigen
  - gflags
  - glog
  - tqdm
  - imgaug
  - pandas
  - tensorboard
  - pip:
    - glumpy==1.1.0

  